In [454]:
from random import randint, shuffle, random
import numpy as np

# Matrice d'adjacence

In [455]:
# Génération de la matrice adjacence à partir d'un fichier
def load_matrix():
    mat = []
    with open('mat_adjacence', 'r') as file:   
        for l in file.readlines():  
            val = [int(x) for x in l.split()]
            mat.append(val)            
    return mat

# Créer une matrice d'adjacence dont le cout du circuit Hamiltonien optimal est celui de la périphérie  
def create_matrix(n_ville):
    mat = np.zeros((n_ville, n_ville))
    
    for i in range(n_ville):
        for j in range(i, n_ville):
            cout = randint(1, 10)
            if i == j:
                cout = 0
            i_after = i+1 if i+1 < n_ville else 0
            if i_after == j:
                cout = 1
                 
            mat[i][j] = cout
            mat[j][i] = cout
    mat[n_ville-1][0] = 1
    mat[0][n_ville-1] = 1

    return mat

Initialisation de la population

In [456]:
def population_init(nb_ville, size):
    population = []
    
    for _ in range(size):
        circuit = list(range(nb_ville))
        shuffle(circuit) # circuit random
        population.append([circuit, 5])
        
    return population



In [457]:

def get_path_cost(cost_mat, path): # Renvoie le coût d'un chemin, par rapport à la matrice d'adjacence
    travel_length = 0
    
    for i in range(0, len(path)):
        depart = path[i-1] # On compte aussi l'arrète entre la premiere et dernière ville (-1 en python -> dernier élément) 
        arrival = path[i]
        travel_length += cost_mat[depart][arrival]
    
    return travel_length  

class Agent:
    def __init__(self, nodes_to_explore, deposit_Q, prob_explore_Y=1, alpha=1, beta=1):
        self.starting_node = 0 # Toute les fourmies commencent au même endroit
        self.deposit_Q = deposit_Q
        self.null_prob = prob_explore_Y 
        # Pour la decision de l'exploration
        self.alpha = 1 # Importance des phéromone
        self.beta = 1 # Importance de la distance d'une ville
        self.reset_exploration(list(nodes_to_explore)) 
    
     
    def reset_exploration(self, nodes_to_explore):
        self.unexplored = nodes_to_explore
        self.unexplored.remove(self.starting_node)
        self.explored = [self.starting_node]
    
    
    def deposite_pheromone(self, mat_cost, pheromone_mat):
        
        pheromone_quantity = self.deposit_Q /  get_path_cost(mat_cost, self.explored)
        
        
        for i in range(1, len(self.explored)):
            depart = self.explored[i-1]
            arrival = self.explored[i]
            
            # On dépose les phéromones sur les arrettes
            pheromone_mat[depart][arrival] += pheromone_quantity
          
          
      
    def choose_next_location(self, mat_cost, mat_pheromone):
        # On choisit la prochaine ville a explorer aléatoirement selon les phéromones,
        # avec une proba non nul qu'on explore une ville jamais exploré par les agents
        # Et retourne un indice parmis la liste des unexplored
        
        depart = self.explored[-1] 
        sum = 0
        
        # On somme les differente pheromone pour avoir les probabilité
        for arrival in self.unexplored:
            
            # On a une proba non nul pour qu'un agent puisse explorer une ville jamais exploré par les autres agents controllé par le parametre Y
            sum += self.null_prob \
                + mat_pheromone[depart][arrival] ** self.alpha \
                + 1/mat_cost[depart][arrival] ** self.beta # ηij la visibilité, qui est égale à l’inverse de la distance de deux villes i et j 
        
        # random qui decide de la prochaine ville à explorer
        r = random() *  sum
        s = 0 
        # Recherche de la ville qui vient d'être choisit
        for i, arrival in enumerate(self.unexplored): 
            s += self.null_prob \
                + mat_pheromone[depart][arrival] ** self.alpha \
                + 1/mat_cost[depart][arrival] ** self.beta
            
            # On s'arrette lorsque l'on a trouvé la prochaine ville, et on retourne son indice dans unexplored
            if s >= r:
                return i
            
    def explore(self, mat_cost, mat_pheromone):
        # Tant qu'on a pas tout exploré
        while len(self.unexplored) > 0:
            # On choisit la prochaine destination parmis ceux qui reste à explorer 
            next_i = self.choose_next_location(mat_cost, mat_pheromone) 
            curr_node = self.unexplored.pop(next_i)
            self.explored.append(curr_node)
            
        # Une fois la tournée terminé, l'agent dépose les phéromones
        self.deposite_pheromone(mat_cost, mat_pheromone)
        # On reset les villes explorer pour pouvoir recommencer l'exploration 
        self.reset_exploration(self.explored)
        
def evaporation(pheromone_mat, disipation_rate):
    for i in range(len(pheromone_mat)):
        for j in range(len(pheromone_mat[0])):
            if pheromone_mat[i][j] > 0:
                pheromone_mat[i][j] -= disipation_rate
                
            

In [462]:
def index_max(arr, exclude_indices): # retourne l'indice dont la valeur est maximal, et qui n'est pas dans exclude_indices
    
    # On n'explore pas a partir du premier, au cas où l'élément 0 fait partir de exclude_indices
    best_i = None 
    for i in range(len(arr)): 
        if best_i == None:
            if i not in exclude_indices: 
                best_i = i
            continue 
        
        if arr[best_i] < arr[i] and i not in exclude_indices:
            best_i = i
            
    return best_i

def find_best(pheromone_mat): # Trouve le chemin le plus parcourus
    res = [0] # On démart à 0, car on cherche un cycle hamiltonien, donc le meilleur circuit passera forcement par cette ville, indépendament de l'ordre.
    # Pour chaque ville
    for _ in range(1, len(pheromone_mat)):
        depart = res[-1]
        arrival = index_max(pheromone_mat[depart], res)
        res.append(arrival)
        
        
    return res


def main():
    size = 10
    epoch_max = 100
    agents_number = 10 
    disipation_rate = 1
    deposit_Q = 1
    prob_explore_Y = 1
    
    mat_cost = create_matrix(size)
    print("matrice d'adjacence")
    print(mat_cost)
    pheromone_mat = np.zeros((size, size))
    agents = [Agent(list(range(size)), deposit_Q, prob_explore_Y) for _ in range(agents_number)]
    
    disipation_rate = 0
    
    for _ in range(epoch_max):
        #print("iteration: ", i)
        # On avance chaque agents dans leurs exploration
        for agent in agents:
            agent.explore(mat_cost, pheromone_mat) # Un agent avance d'un noeud
        # On évapore les phéromones a chaque fin d'itération
        evaporation(pheromone_mat, disipation_rate)
    
    best_path = find_best(pheromone_mat) 
    print("Meilleur chemin: ", best_path)
    print("Cout: ", get_path_cost(mat_cost, best_path))
    
main()

matrice d'adjacence
[[ 0.  1.  7.  9.  7.  3.  4.  2. 10.  1.]
 [ 1.  0.  1.  7.  5.  9.  4. 10.  1.  4.]
 [ 7.  1.  0.  1.  2.  9.  9.  6.  7.  9.]
 [ 9.  7.  1.  0.  1.  3.  7.  7.  8.  5.]
 [ 7.  5.  2.  1.  0.  1.  3.  3.  1.  7.]
 [ 3.  9.  9.  3.  1.  0.  1. 10.  9.  1.]
 [ 4.  4.  9.  7.  3.  1.  0.  1.  4.  5.]
 [ 2. 10.  6.  7.  3. 10.  1.  0.  1.  7.]
 [10.  1.  7.  8.  1.  9.  4.  1.  0.  1.]
 [ 1.  4.  9.  5.  7.  1.  5.  7.  1.  0.]]
Meilleur chemin:  [0, 9, 5, 6, 7, 8, 4, 3, 2, 1]
Cout:  10.0
