In [1]:
from algo_gen import algo_genetique
from algo_four import algo_fourmis
import numpy as np
from random import randint

In [2]:
# Chargement de la matrice adjacence à partir d'un fichier
def load_matrix():
    mat = []
    with open('mat_adjacence', 'r') as file:   
        for l in file.readlines():  
            val = [int(x) for x in l.split()]
            mat.append(val)            
    return mat

# Créer une matrice d'adjacence dont le cout du circuit Hamiltonien optimal est celui de la périphérie  
def create_matrix(n_ville):
    mat = np.zeros((n_ville, n_ville))
    
    for i in range(n_ville):
        for j in range(i, n_ville):
            cout = randint(2, 10)
            if i == j:
                cout = 0
            i_after = i+1 if i+1 < n_ville else 0
            if i_after == j:
                cout = 1
                 
            mat[i][j] = cout
            mat[j][i] = cout
    mat[n_ville-1][0] = 1
    mat[0][n_ville-1] = 1

    return mat
 

In [3]:
algo_fourmis(create_matrix(10), verbal=True)

Matrice d'adjacence:
[[ 0.  1.  5.  7.  3.  8. 10.  5.  3.  1.]
 [ 1.  0.  1.  3.  9.  4.  9.  8.  5.  5.]
 [ 5.  1.  0.  1.  4.  8. 10.  5.  7.  2.]
 [ 7.  3.  1.  0.  1.  5.  9.  9.  7. 10.]
 [ 3.  9.  4.  1.  0.  1.  4.  2. 10.  5.]
 [ 8.  4.  8.  5.  1.  0.  1.  9.  7. 10.]
 [10.  9. 10.  9.  4.  1.  0.  1.  8.  8.]
 [ 5.  8.  5.  9.  2.  9.  1.  0.  1.  8.]
 [ 3.  5.  7.  7. 10.  7.  8.  1.  0.  1.]
 [ 1.  5.  2. 10.  5. 10.  8.  8.  1.  0.]]
iteration:  0 , meilleurs chemins: 10.0
iteration:  1 , meilleurs chemins: 10.0
iteration:  2 , meilleurs chemins: 10.0
iteration:  3 , meilleurs chemins: 10.0
iteration:  4 , meilleurs chemins: 10.0
iteration:  5 , meilleurs chemins: 10.0
iteration:  6 , meilleurs chemins: 10.0
iteration:  7 , meilleurs chemins: 10.0
iteration:  8 , meilleurs chemins: 10.0
iteration:  9 , meilleurs chemins: 10.0
iteration:  10 , meilleurs chemins: 10.0
iteration:  11 , meilleurs chemins: 10.0
iteration:  12 , meilleurs chemins: 10.0
iteration:  13 , meilleur

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 10.0)

In [4]:
algo_genetique(create_matrix(10), time_max=10000, verbal=True)

[[ 0.  1.  9.  9.  4. 10.  3.  2. 10.  1.]
 [ 1.  0.  1.  5.  4.  7.  7.  7.  5.  5.]
 [ 9.  1.  0.  1.  6.  2.  9.  8.  4.  8.]
 [ 9.  5.  1.  0.  1.  8.  9.  2.  3.  5.]
 [ 4.  4.  6.  1.  0.  1.  4.  8.  8.  9.]
 [10.  7.  2.  8.  1.  0.  1.  3.  5.  6.]
 [ 3.  7.  9.  9.  4.  1.  0.  1.  9. 10.]
 [ 2.  7.  8.  2.  8.  3.  1.  0.  1. 10.]
 [10.  5.  4.  3.  8.  5.  9.  1.  0.  1.]
 [ 1.  5.  8.  5.  9.  6. 10. 10.  1.  0.]]
iteration: 1 , nb individu: 10 val_min : 43.0
iteration: 2 , nb individu: 10 val_min : 43.0
iteration: 3 , nb individu: 9 val_min : 43.0
iteration: 4 , nb individu: 9 val_min : 50.0
iteration: 5 , nb individu: 10 val_min : 53.0
iteration: 6 , nb individu: 8 val_min : 44.0
iteration: 7 , nb individu: 7 val_min : 44.0
iteration: 8 , nb individu: 8 val_min : 31.0
iteration: 9 , nb individu: 9 val_min : 44.0
iteration: 10 , nb individu: 9 val_min : 44.0
iteration: 11 , nb individu: 2 val_min : 61.0
iteration: 12 , nb individu: 7 val_min : 61.0
iteration: 13 , nb indi

UnboundLocalError: local variable 'chemin' referenced before assignment