In [1]:
from algo_gen import algo_genetique
from algo_four import algo_fourmis
import numpy as np
from random import randint

In [2]:
# Chargement de la matrice adjacence à partir d'un fichier
def load_matrix():
    mat = []
    with open('mat_adjacence', 'r') as file:   
        for l in file.readlines():  
            val = [int(x) for x in l.split()]
            mat.append(val)            
    return mat

# Créer une matrice d'adjacence dont le cout du circuit Hamiltonien optimal est celui de la périphérie  
def create_matrix(n_ville):
    mat = np.zeros((n_ville, n_ville))
    
    for i in range(n_ville):
        for j in range(i, n_ville):
            cout = randint(2, 10)
            if i == j:
                cout = 0
            i_after = i+1 if i+1 < n_ville else 0
            if i_after == j:
                cout = 1
                 
            mat[i][j] = cout
            mat[j][i] = cout
    mat[n_ville-1][0] = 1
    mat[0][n_ville-1] = 1

    return mat
 

In [3]:
algo_fourmis(create_matrix(7), verbal=True)

Matrice d'adjacence:
[[ 0.  1.  9.  4.  5.  6.  1.]
 [ 1.  0.  1.  4.  2.  8.  8.]
 [ 9.  1.  0.  1.  4. 10.  5.]
 [ 4.  4.  1.  0.  1.  3.  5.]
 [ 5.  2.  4.  1.  0.  1.  8.]
 [ 6.  8. 10.  3.  1.  0.  1.]
 [ 1.  8.  5.  5.  8.  1.  0.]]
iteration:  0 , meilleurs chemins: 7.0
iteration:  1 , meilleurs chemins: 7.0
iteration:  2 , meilleurs chemins: 7.0
iteration:  3 , meilleurs chemins: 7.0
iteration:  4 , meilleurs chemins: 7.0
iteration:  5 , meilleurs chemins: 7.0
iteration:  6 , meilleurs chemins: 7.0
iteration:  7 , meilleurs chemins: 7.0
iteration:  8 , meilleurs chemins: 7.0
iteration:  9 , meilleurs chemins: 7.0
iteration:  10 , meilleurs chemins: 7.0
iteration:  11 , meilleurs chemins: 7.0
iteration:  12 , meilleurs chemins: 7.0
iteration:  13 , meilleurs chemins: 7.0
iteration:  14 , meilleurs chemins: 7.0
iteration:  15 , meilleurs chemins: 7.0
iteration:  16 , meilleurs chemins: 7.0
iteration:  17 , meilleurs chemins: 7.0
iteration:  18 , meilleurs chemins: 7.0
iteration: 

([0, 6, 5, 4, 3, 2, 1], 7.0)

In [4]:
algo_genetique(create_matrix(7), time_max=100, verbal=True)

[[ 0.  1.  7.  6.  2.  6.  1.]
 [ 1.  0.  1.  8. 10. 10.  3.]
 [ 7.  1.  0.  1.  5.  9. 10.]
 [ 6.  8.  1.  0.  1.  7.  3.]
 [ 2. 10.  5.  1.  0.  1. 10.]
 [ 6. 10.  9.  7.  1.  0.  1.]
 [ 1.  3. 10.  3. 10.  1.  0.]]
iteration: 1 , nb individu: 20 val_min : 18.0
iteration: 2 , nb individu: 20 val_min : 23.0
iteration: 3 , nb individu: 20 val_min : 7.0
iteration: 4 , nb individu: 20 val_min : 15.0
iteration: 5 , nb individu: 19 val_min : 7.0
iteration: 6 , nb individu: 20 val_min : 7.0
iteration: 7 , nb individu: 15 val_min : 7.0
iteration: 8 , nb individu: 20 val_min : 7.0
iteration: 9 , nb individu: 20 val_min : 7.0
iteration: 10 , nb individu: 20 val_min : 7.0
iteration: 11 , nb individu: 15 val_min : 7.0
iteration: 12 , nb individu: 18 val_min : 7.0
iteration: 13 , nb individu: 20 val_min : 7.0
iteration: 14 , nb individu: 18 val_min : 7.0
iteration: 15 , nb individu: 19 val_min : 7.0
iteration: 16 , nb individu: 19 val_min : 7.0
iteration: 17 , nb individu: 16 val_min : 7.0
iterat

([2, 1, 0, 6, 3, 4, 5], 17.0)

In [5]:
def test_acc(mat_size = 5, n_try=1): 
    """
    Test avec des matrice dont le chemin au cout optimal correspond à la périphérie, et retourne l'accuracy moyen
        mat_size : taille de la matrice d'adjacence qui sera exploré
        n_try : Nombre de test effectué
    """
    # taille optimal = size    

    genetique_acc = 0
    fourmis_acc = 0
    # On test plusieurs fois et on obtient
    for _ in range(n_try):
        cost_mat = create_matrix(mat_size)
        # Accuracy = chemin trouvé par l'algo / meilleur chemin 
        genetique_acc += mat_size / algo_genetique(cost_mat)[1]
        fourmis_acc += mat_size / algo_fourmis(cost_mat)[1]
        
    return genetique_acc / n_try, fourmis_acc / n_try

test_acc(mat_size=7, n_try=10)

(0.9083333333333332, 1.0)